### PR TITLE
Lab-06 Last Piece Edits

### PR DESCRIPTION
**Pull request by TommyLiang1**
Tidied up the formatting of your code and added some extra comments

### CODE REVIEW

**Comment by TanmoyPaul1** [comment]
Your comments are helpful. Do you think I should have more? 
[https://github.com/TommyLiang1/fall-2020-135-lab-06-TanmoyPaul1/blob/29b3f3f59b1163174a5df0b378047eabc288efe5/decode.cpp#L10](url) 

How dare you make yourself an editor

**Comment by TanmoyPaul1** [comment]
https://github.com/TommyLiang1/fall-2020-135-lab-06-TanmoyPaul1/blob/29b3f3f59b1163174a5df0b378047eabc288efe5/decode.cpp#L10

**Comment by TommyLiang1** [comment]
I'm glad the comments are helpful. What do you mean by the question that follows? If it is about your commenting, then yes add more comments to make your code more readable.

**Review by TanmoyPaul1 — APPROVED** [review]
Thank you for your changes.

**Pull request merged**
